name: Build and deploy Python app to Azure Web App - upangsfmebackend

on:
  push:
    branches:
      - newbackend
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (sanity check)
        run: |
          python -m pip install --upgrade pip
          python -c "import sys; print(sys.version)"
          test -f requirements.txt
          pip install -r requirements.txt

      - name: Create deployment zip
        run: |
          zip -r release.zip . -x ".git/*" ".github/*" "antenv/*" "__pycache__/*" "*.pyc"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CAD3CFA118CD436E8BA60F8AEE1EDFEF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CDA5510428B94AF59B1909B932B3F208 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A26AC04E3BC436C8E0121624E24F957 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "upangsfmebackend"
          slot-name: "Production"
          package: release.zip